<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://itg.santander.cl/AppEvaluadorRiesgo_Persona/Services/wsCL1CO_CONEVALUADORDERIESGO" xmlns:pfx0="http://www.tibco.com/schemas/APPEVALUADORRIESGO_PERSONA_DEV/Resources/Schemas/CONEVALUADORDERIESGO.xsd" targetNamespace="http://itg.santander.cl/AppEvaluadorRiesgo_Persona/Services/wsCL1CO_CONEVALUADORDERIESGO">
    <import namespace="http://www.tibco.com/schemas/APPEVALUADORRIESGO_PERSONA_DEV/Resources/Schemas/CONEVALUADORDERIESGO.xsd" location="../Resources/Schemas/CONEVALUADORDERIESGO.xsd"/>
    <message name="INPUT">
        <part element="pfx0:INPUT" name="parameters"/>
    </message>
    <message name="OUTPUT">
        <part element="pfx0:OUTPUT" name="parameters"/>
    </message>
    <portType name="portType">
        <operation name="getEVALUADORDERIESGO">
            <input message="tns:INPUT"/>
            <output message="tns:OUTPUT"/>
        </operation>
    </portType>
</definitions>